default_platform(:android)

platform :android do
  desc "Submit a new Internal Build to Play Store internal track"
  lane :internal do
      keystore_file_path = ENV["PLAY_STORE_UPLOAD_KEY"] || raise("Keystore file path not found in secrets")

      gradle(
        task: "assembleRelease",
        properties: {
          "android.injected.signing.store.file" => keystore_file_path,
          "android.injected.signing.store.password" => ENV["KEYSTORE_STORE_PASSWORD"],
          "android.injected.signing.key.alias" => ENV["KEYSTORE_KEY_ALIAS"],
          "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"]
        }
      )

    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
    )
  end
end
