name: Deploy to Play Store

on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "internal"
        type: choice
        options:
          - beta
          - promote_to_production
          - internal

# Declare default permissions as read-only.
permissions: read-all

jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository code
        uses: actions/checkout@v2

      # Setup Java and Gradle
      - name: Setup Java and Gradle
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # Configure Keystore
      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=app/upload-keystore.jks" > app/key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> app/key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> app/key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> app/key.properties
          # Debug: Print keystore file content and key.properties
                   ls -la app/
                   cat app/key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

#      - name: Install npm dependencies
#        run: |
#            yarn install
#
#      - uses: ruby/setup-ruby@v1
#        with:
#           ruby-version: '3.0.7'
#           bundler-cache: true
#
#      # Setup Ruby
##      - uses: actions/setup-ruby@v1
##        with:
##          ruby-version: '2.6'
#
#      # Install Bundler
#      - name: Install Bundler
#        run: gem install bundler
#
##      # Navigate to the app directory
##      - name: Change directory to app and install dependencies
##        working-directory: ./app
##
#
#      # Run Fastlane
#      - name: Run fastlane
#
#        run: |
#          bundle install
#          chmod +x gradlew
#          bundle exec fastlane ${{ github.event.inputs.lane || 'internal' }}
#        env:
#          FASTLANE_JSON_KEY_FILE: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
